from __future__ import annotations

from dataclasses import dataclass


ACT_DAILY_STAGE_SOURCE = 'analysis/mediafire_20260620/apk_extract/assets/3BAO/7633aad8b4929bd2, ./script/setting/act/act_daily_stage_cfg.lua, parsed 2026-06-23'
ACT_DAILY_TOTAL_LIMIT = 65


@dataclass(frozen=True, slots=True)
class ActDailyStageDefinition:
    stage_id: int
    section: str
    display_order: int
    sub_id: int
    name: str
    member_ids: tuple[int, ...]
    member_shape_ids: tuple[int, ...]
    constant_index: int

    @property
    def label(self) -> str:
        if self.name:
            return self.name
        return f'{self.section} {self.stage_id}'

    def as_dict(self) -> dict[str, object]:
        return {
            'StageId': self.stage_id,
            'Section': self.section,
            'DisplayOrder': self.display_order,
            'SubId': self.sub_id,
            'Name': self.name,
            'MemberIds': list(self.member_ids),
            'MemberShapeIds': list(self.member_shape_ids),
            'TotalLimit': ACT_DAILY_TOTAL_LIMIT,
            'Source': ACT_DAILY_STAGE_SOURCE,
        }


@dataclass(frozen=True, slots=True)
class ActDailyMonsterDefinition:
    monster_id: int
    display_name: str
    constant_index: int


ACT_DAILY_STAGES = tuple(
    ActDailyStageDefinition(**item)
    for item in [{'stage_id': 860001,
  'section': 'daily_stage',
  'display_order': 1,
  'sub_id': 0,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 18},
 {'stage_id': 860002,
  'section': 'daily_stage',
  'display_order': 2,
  'sub_id': 3,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 22},
 {'stage_id': 860003,
  'section': 'daily_stage',
  'display_order': 3,
  'sub_id': 35,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 25},
 {'stage_id': 860004,
  'section': 'daily_stage',
  'display_order': 4,
  'sub_id': 5,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 28},
 {'stage_id': 860005,
  'section': 'daily_stage',
  'display_order': 5,
  'sub_id': 6,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 30},
 {'stage_id': 860006,
  'section': 'daily_stage',
  'display_order': 6,
  'sub_id': 7,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 32},
 {'stage_id': 860007,
  'section': 'daily_stage',
  'display_order': 7,
  'sub_id': 8,
  'name': '',
  'member_ids': (1026, 1236, 1146, 1106),
  'member_shape_ids': (36001, 36002, 36003, 36004),
  'constant_index': 34},
 {'stage_id': 880001,
  'section': 'named_daily_challenge',
  'display_order': 8,
  'sub_id': 9,
  'name': '切岛锐儿郎',
  'member_ids': (1156, 1206, 1066),
  'member_shape_ids': (36005, 36006, 36007),
  'constant_index': 49},
 {'stage_id': 880002,
  'section': 'named_daily_challenge',
  'display_order': 9,
  'sub_id': 10,
  'name': '八百万百',
  'member_ids': (1216, 1246),
  'member_shape_ids': (36008, 36009),
  'constant_index': 59},
 {'stage_id': 880003,
  'section': 'named_daily_challenge',
  'display_order': 10,
  'sub_id': 11,
  'name': '轰焦冻',
  'member_ids': (1086, 1136, 1076),
  'member_shape_ids': (36010, 36011, 36012),
  'constant_index': 67},
 {'stage_id': 880004,
  'section': 'named_daily_challenge',
  'display_order': 11,
  'sub_id': 12,
  'name': '爆豪胜己',
  'member_ids': (1046,),
  'member_shape_ids': (36013,),
  'constant_index': 77},
 {'stage_id': 880005,
  'section': 'named_daily_challenge',
  'display_order': 12,
  'sub_id': 13,
  'name': '安德瓦',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 83},
 {'stage_id': 880006,
  'section': 'named_daily_challenge',
  'display_order': 13,
  'sub_id': 14,
  'name': '斯坦因',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 87},
 {'stage_id': 880007,
  'section': 'named_daily_challenge',
  'display_order': 14,
  'sub_id': 20,
  'name': '欧尔麦特',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 91},
 {'stage_id': 890001,
  'section': 'awake_daily_challenge',
  'display_order': 15,
  'sub_id': 21,
  'name': '',
  'member_ids': (1025,),
  'member_shape_ids': (37002,),
  'constant_index': 93},
 {'stage_id': 890002,
  'section': 'awake_daily_challenge',
  'display_order': 16,
  'sub_id': 22,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 97},
 {'stage_id': 890003,
  'section': 'awake_daily_challenge',
  'display_order': 17,
  'sub_id': 23,
  'name': '',
  'member_ids': (1085,),
  'member_shape_ids': (37003,),
  'constant_index': 99},
 {'stage_id': 890004,
  'section': 'awake_daily_challenge',
  'display_order': 18,
  'sub_id': 24,
  'name': '',
  'member_ids': (1245,),
  'member_shape_ids': (37004,),
  'constant_index': 103},
 {'stage_id': 890005,
  'section': 'awake_daily_challenge',
  'display_order': 19,
  'sub_id': 30,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 107},
 {'stage_id': 860011,
  'section': 'daily_stage_extra',
  'display_order': 20,
  'sub_id': 31,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 109},
 {'stage_id': 860012,
  'section': 'daily_stage_extra',
  'display_order': 21,
  'sub_id': 32,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 111},
 {'stage_id': 860013,
  'section': 'daily_stage_extra',
  'display_order': 22,
  'sub_id': 33,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 113},
 {'stage_id': 860014,
  'section': 'daily_stage_extra',
  'display_order': 23,
  'sub_id': 34,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 115},
 {'stage_id': 860015,
  'section': 'daily_stage_extra',
  'display_order': 24,
  'sub_id': 0,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 117},
 {'stage_id': 860016,
  'section': 'daily_stage_extra',
  'display_order': 25,
  'sub_id': 36,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 118},
 {'stage_id': 860017,
  'section': 'daily_stage_extra',
  'display_order': 26,
  'sub_id': 48,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 120},
 {'stage_id': 882001,
  'section': 'snowman_daily_challenge',
  'display_order': 27,
  'sub_id': 49,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 122},
 {'stage_id': 882002,
  'section': 'snowman_daily_challenge',
  'display_order': 28,
  'sub_id': 50,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 124},
 {'stage_id': 882003,
  'section': 'snowman_daily_challenge',
  'display_order': 29,
  'sub_id': 51,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 126},
 {'stage_id': 882004,
  'section': 'snowman_daily_challenge',
  'display_order': 30,
  'sub_id': 52,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 128},
 {'stage_id': 882005,
  'section': 'snowman_daily_challenge',
  'display_order': 31,
  'sub_id': 53,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 130},
 {'stage_id': 882006,
  'section': 'snowman_daily_challenge',
  'display_order': 32,
  'sub_id': 54,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 132},
 {'stage_id': 882007,
  'section': 'snowman_daily_challenge',
  'display_order': 33,
  'sub_id': 55,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 134},
 {'stage_id': 882008,
  'section': 'snowman_daily_challenge',
  'display_order': 34,
  'sub_id': 0,
  'name': '',
  'member_ids': (),
  'member_shape_ids': (),
  'constant_index': 136}]
)

ACT_DAILY_STAGE_BY_ID = {stage.stage_id: stage for stage in ACT_DAILY_STAGES}

ACT_DAILY_MONSTERS = tuple(
    ActDailyMonsterDefinition(**item)
    for item in [{'monster_id': 2005, 'display_name': '巨大化敌人', 'constant_index': 152},
 {'monster_id': 2051, 'display_name': '清道夫', 'constant_index': 157},
 {'monster_id': 3003, 'display_name': '印斯茅斯', 'constant_index': 161},
 {'monster_id': 2206, 'display_name': '黑马刀流', 'constant_index': 164},
 {'monster_id': 2044, 'display_name': 'ѐ�水狗小队', 'constant_index': 168},
 {'monster_id': 3007, 'display_name': '脑无', 'constant_index': 170},
 {'monster_id': 3115, 'display_name': '', 'constant_index': 174},
 {'monster_id': 3127, 'display_name': '', 'constant_index': 175},
 {'monster_id': 3108, 'display_name': '', 'constant_index': 177},
 {'monster_id': 3113, 'display_name': '', 'constant_index': 178},
 {'monster_id': 3110, 'display_name': '', 'constant_index': 180},
 {'monster_id': 3022, 'display_name': '', 'constant_index': 181},
 {'monster_id': 3112, 'display_name': '', 'constant_index': 184}]
)

ACT_DAILY_MONSTER_IDS = tuple(monster.monster_id for monster in ACT_DAILY_MONSTERS)

