from __future__ import annotations

from dataclasses import dataclass

from .characters import PlayableCharacter


CHARACTER_ARCHIVE_SOURCE = (
    "My Hero Academia The Strongest Hero Playable Character Archive.docx, "
    "Deep Research export inspected 2026-06-25"
)


@dataclass(frozen=True, slots=True)
class CharacterArchiveEntry:
    model_asset_id: str
    canonical_name: str
    quirk: str
    hero_type: str
    base_rank: str
    skills_captured: str
    passives_captured: str
    talents_captured: str
    completeness: str
    source_ref: str
    role_note: str
    kit_note: str
    data_gaps: tuple[str, ...] = ()

    @property
    def is_high_confidence(self) -> bool:
        return self.completeness.lower() == "high"

    @property
    def has_medium_or_better_kit_coverage(self) -> bool:
        return self.completeness.lower() in {"high", "medium"}


CHARACTER_ARCHIVE_BY_MODEL = {
    "h1003": CharacterArchiveEntry(
        "h1003",
        "All Might",
        "One For All",
        "Power",
        "S",
        "10",
        "6",
        "15",
        "Medium",
        "[7]/[33]",
        "S-tier PvE/PvP bruiser; community build priority ATK, Crit, Crit DMG, Power.",
        "Confirmed kit includes Heavy Strike, Detroit Smash, New Hampshire Smash, I Am Here!, Power Blast, Justice Punch, Expert Counter, Transferred Might, and United States of Smash.",
        ("base/max stat tables",),
    ),
    "h1012": CharacterArchiveEntry(
        "h1012",
        "Dabi",
        "not exposed in reviewed page body",
        "Technical",
        "S",
        "10",
        "6",
        "15",
        "Medium",
        "[8]/[34]",
        "Offensive burn/burst Technical unit; build note is community-derived.",
        "Community sources preserve Flame, Ignite, Sea of Flame, Scorch, Flame Punch, Enflame, Burning Counter, Snake of Flame, and Flame Burial.",
        ("official stat tables", "complete numeric effects"),
    ),
    "h1010": CharacterArchiveEntry(
        "h1010",
        "Denki Kaminari",
        "Electrification",
        "Technical",
        "B",
        "6",
        "2 partial",
        "2 partial",
        "Low",
        "[9]/[35]",
        "PvE-leaning offensive Technical unit.",
        "Confirmed skills include Electric Surge, Lightning Bolt, Charged Bolt, Indiscriminate Shock, Dodge, and Thunder Strike.",
        ("full passive coverage", "full talent coverage"),
    ),
    "h1013": CharacterArchiveEntry(
        "h1013",
        "Eijiro Kirishima",
        "Hardening",
        "Power",
        "B",
        "5",
        "2 partial",
        "2 partial",
        "Low",
        "[10]/[36]",
        "Bruiser/counter-pick with offense plus survivability.",
        "Confirmed skills include Red Charge, Red Rush, Red Rodeo, Red Gauntlet, and Red Riot Hammer.",
        ("exact multipliers", "official stat tables"),
    ),
    "h1021": CharacterArchiveEntry(
        "h1021",
        "Endeavor",
        "Hellflame",
        "Technical",
        "S",
        "13",
        "6",
        "2 confirmed",
        "Medium",
        "[11]/[37]",
        "Offense-first Technical lance/flame unit.",
        "Kit record includes Crackling Combo, Fire Lance, Exploding Lance, Consuming Flame, Piercing Lance, Flashfire Fist, Flashfire Pillar, Imploding Strike, Flame Resurge, Scorching Counter, Flame Dash, and Hell Lance.",
        ("public English character-specific patch logs",),
    ),
    "h1022": CharacterArchiveEntry(
        "h1022",
        "Fumikage Tokoyami",
        "Dark Shadow",
        "Speed",
        "S",
        "10",
        "6",
        "2 confirmed",
        "Medium",
        "[12]/[38]",
        "Speed bruiser/control unit with anti-air and durability notes.",
        "Confirmed skills include Shadow Strike, Shadow Latch, Liberation, Night Hunter, Shadow Frenzy, Abyssal Talons, Piercing Shadow, Shadow Nature, Fleeting Assault, Talon Dash, and Black Sabbath.",
        ("public stat tables",),
    ),
    "h1026": CharacterArchiveEntry(
        "h1026",
        "Hawks",
        "Fierce Wings",
        "Speed",
        "S",
        "10",
        "6",
        "15",
        "Medium",
        "[13]/[39]",
        "Mobile marked-target assassin/skirmisher.",
        "Confirmed skills include Feather Combo, Air Combo, Feather Storm, Feather Mark, Disperse, Downfall, Spiral Strike, Feather Regeneration, Fast Counter, Eagle Strike, and Sky High.",
        ("complete official passive text sheet",),
    ),
    "h1001": CharacterArchiveEntry(
        "h1001",
        "Izuku Midoriya",
        "One For All",
        "Speed",
        "B",
        "10",
        "6",
        "15",
        "High",
        "[14]/[40]",
        "Starter Speed unit; recommended build prioritizes ATK, Crit, Crit DMG, Speed.",
        "Highest-confidence archive entry; page preserves move descriptions, formulas, cooldown examples, and resonance passive unlock ranks.",
        (),
    ),
    "h1002": CharacterArchiveEntry(
        "h1002",
        "Katsuki Bakugo",
        "Explosion",
        "Power",
        "S",
        "5 core-confirmed",
        "not recovered",
        "3 confirmed",
        "Low",
        "[15]/[41]",
        "Burst-oriented Power unit; build note is community-derived.",
        "Core attacks confirmed include Explosion Combo, Burst Bullet, Burning Fist, and Howitzer Impact.",
        ("full skill/passive body",),
    ),
    "h1016": CharacterArchiveEntry(
        "h1016",
        "Mashirao Ojiro",
        "Tail",
        "Power",
        "A",
        "10",
        "6",
        "3 confirmed",
        "Medium",
        "[16]/[42]",
        "Combo-oriented close-range striker.",
        "Move set includes Tail Punches, Tailspin: Double Sweep, Tail & Foot: Kicks, Tailflash: Whiz, Tail Smash, Empty Step, Martial Realm, Tail Counter, Tail Sweep, and Tailfist: Swamp Smack Spin.",
        ("numeric effect details",),
    ),
    "h1017": CharacterArchiveEntry(
        "h1017",
        "Mina Ashido",
        "Acid",
        "Technical",
        "A",
        "10",
        "6",
        "not recovered",
        "Medium",
        "[17]/[43]",
        "Technical AOE/field-control DPS.",
        "Confirmed kit includes Acid Combo, Acid Tornado, Acid Bomb, Acid Surf, Acid Flare, Acid Bullet, Acid Strike, Acid Counter, Rapid Secretion, and Acid Current.",
        ("talent coverage",),
    ),
    "h1020": CharacterArchiveEntry(
        "h1020",
        "Minoru Mineta",
        "Pop Off",
        "Technical",
        "A",
        "3 core-confirmed",
        "2 confirmed",
        "2 confirmed",
        "Low",
        "[18]/[44]",
        "Utility/control unit rather than raw DPS.",
        "Confirmed skills include Fearful Combo, Grape Rush, and Mineta-Bounce; confirmed passives include Opposite Attraction and High as a Kite.",
        ("full passive ladder", "formulas", "official stat tables"),
    ),
    "h1009": CharacterArchiveEntry(
        "h1009",
        "Momo Yaoyorozu",
        "Creation",
        "Technical",
        "S",
        "not recovered",
        "1 confirmed",
        "2 confirmed",
        "Low",
        "[19]/[45]",
        "Support-DPS / summon-control unit.",
        "Community pages confirm Goddess Loadout, Improved Scythe, and Cannon Barrage: Support.",
        ("full public move list",),
    ),
    "h1007": CharacterArchiveEntry(
        "h1007",
        "Ochaco Uraraka",
        "Zero Gravity",
        "Power",
        "A",
        "7 core-confirmed",
        "1 confirmed",
        "1 confirmed",
        "Medium",
        "[20]/[46]",
        "Power unit with flight and anti-melee utility.",
        "Confirmed components include Martial Combo, Floating Combo, Comet, Fierce Counter, Meteor Storm, Comet Home Run, Uravity GMA, and Uravity Rush.",
        (),
    ),
    "h1019": CharacterArchiveEntry(
        "h1019",
        "Tomura Shigaraki",
        "Decay",
        "Technical",
        "S",
        "mechanic only",
        "1 confirmed",
        "2 confirmed",
        "Low",
        "[21]/[47]",
        "Limited villain control/DPS.",
        "Best preserved mechanic is Rush of Spite, which can summon a Nomu for 15 seconds when the Spite bar is full.",
        ("full move coverage", "full passive coverage"),
    ),
    "h1015": CharacterArchiveEntry(
        "h1015",
        "Shota Aizawa",
        "Erasure",
        "Speed",
        "S",
        "10",
        "6",
        "15",
        "Medium",
        "[22]/[48]",
        "High-value PvP Speed unit with stance/control pressure.",
        "Community sources preserve ten active/stance skills, six passives, and fifteen talents; Fast Rhythm, Sneak: Illusion, Logic, and Tactical Counter: Vigilance have preserved mechanical notes.",
        (),
    ),
    "h1008": CharacterArchiveEntry(
        "h1008",
        "Shoto Todoroki",
        "Half-Cold Half-Hot",
        "Technical",
        "S",
        "3 core-confirmed",
        "not recovered",
        "1 confirmed",
        "Low",
        "[23]/[49]",
        "Control-oriented Technical unit.",
        "Confirmed components include Ice & Fire Combo, Flame Blast, Ice Wall, and Fire One-Two.",
        ("full passive coverage",),
    ),
    "h1110": CharacterArchiveEntry(
        "h1110",
        "Stain",
        "Bloodcurdle",
        "Speed",
        "S",
        "10",
        "6",
        "2 confirmed",
        "Medium",
        "[24]/[50]",
        "Assassin/control duelist with combo-uptime emphasis.",
        "Community pages preserve Cull, Aura of Fear, Dagger Strike, Blade Dance, Break, Bloodcurdle, Shadowy Surprise, Flash, and Verdict.",
        (),
    ),
    "h1006": CharacterArchiveEntry(
        "h1006",
        "Tenya Iida",
        "Engine",
        "Speed",
        "A",
        "3 core-confirmed",
        "1 confirmed",
        "3 confirmed",
        "Low",
        "[25]/[51]",
        "Sustained combo Speed DPS.",
        "Public entries confirm Boost Combo, Recipro Active, Recipro Extend, Ingenium Armor, Realization, and Hyped Up.",
        ("specific formulas", "full passive ladder"),
    ),
    "h1014": CharacterArchiveEntry(
        "h1014",
        "Tsuyu Asui",
        "Frog",
        "Speed",
        "A",
        "10",
        "6",
        "3 confirmed",
        "Medium",
        "[26]/[52]",
        "Mobile poison DPS with invisibility and leap utility.",
        "Community sources preserve Ribbiting Combo, Tongue Capture, Numbing Venom, Tongue Swipe, Piercing Hop, Charging Hop, Counter Kick, Amphibian Camouflage, and Frog Kick.",
        (),
    ),
    "h1027": CharacterArchiveEntry(
        "h1027",
        "WHM Izuku Midoriya",
        "One For All",
        "Speed",
        "S",
        "not recovered",
        "not recovered",
        "not recovered",
        "Low",
        "[27]",
        "World Heroes Mission limited event variant with Blackwhip identity note.",
        "Event page confirms collab window October 27, 2021 through December 15, 2021.",
        ("full parsed move list",),
    ),
    "h1029": CharacterArchiveEntry(
        "h1029",
        "WHM Shoto Todoroki",
        "Half-Cold Half-Hot",
        "Technical",
        "S",
        "not recovered",
        "not recovered",
        "not recovered",
        "Low",
        "[28]",
        "World Heroes Mission limited event variant.",
        "Confirmed as separate from base Shoto and released during the same collab event period.",
        ("full parsed move/passive/talent tables",),
    ),
    "h1028": CharacterArchiveEntry(
        "h1028",
        "WHM Katsuki Bakugo",
        "Explosion",
        "Power",
        "S",
        "not recovered",
        "not recovered",
        "not recovered",
        "Low",
        "[29]",
        "World Heroes Mission limited event variant.",
        "Confirmed as the final WHM event character with a new move set separate from base Bakugo.",
        ("full move/passive details",),
    ),
    "h1032": CharacterArchiveEntry(
        "h1032",
        "Mirio Togata",
        "Permeation",
        "Power",
        "S",
        "2 core-confirmed",
        "2 confirmed",
        "3 confirmed",
        "Medium",
        "[30]/[53]",
        "Burst/bruiser play around permeation.",
        "Dedicated pages confirm The Protector, Against All Odds, Morale Boost, Flashing Combination, and Power Punches.",
        (),
    ),
    "h1030": CharacterArchiveEntry(
        "h1030",
        "Nejire Hado",
        "Wave Motion",
        "Power",
        "S",
        "10",
        "6",
        "1 confirmed",
        "Medium",
        "[31]/[54]",
        "Ranged/burst shockwave pressure.",
        "Coverage includes Wave Combo, Wave Blast, Spinning Up, Charging Wave, Shattering Waves, Vitality Booster, Waving Counter, Arc Dash, and Nejire Wave.",
        (),
    ),
    "h1031": CharacterArchiveEntry(
        "h1031",
        "Tamaki Amajiki",
        "Manifest",
        "Technical",
        "S",
        "not recovered",
        "not recovered",
        "3 confirmed",
        "Low",
        "[32]/[55]",
        "First-anniversary limited/event character.",
        "Dedicated talent pages preserve at least Clamoring Attack, Manifesting Raid, and Vast Hybrid: Extreme.",
        ("full parsed move/passive table",),
    ),
}


def archive_entry_for_character(
    character: PlayableCharacter,
) -> CharacterArchiveEntry | None:
    return CHARACTER_ARCHIVE_BY_MODEL.get(character.model_asset_id)


def archive_entry_for_model(model_asset_id: str) -> CharacterArchiveEntry | None:
    return CHARACTER_ARCHIVE_BY_MODEL.get(str(model_asset_id))

