from __future__ import annotations

from dataclasses import dataclass


DRAMA_FAMILY_STAGE_SOURCE = 'analysis/intro_qte_asset_index.txt, grouped nonnumeric drama families, parsed 2026-06-24'


@dataclass(frozen=True, slots=True)
class DramaFamilyStageDefinition:
    key: str
    label: str
    scripts: tuple[str, ...]


DRAMA_FAMILY_STAGES = tuple(
    DramaFamilyStageDefinition(**item)
    for item in [{'key': 'activity_misc_drama_scripts',
  'label': 'activity and event drama scripts without recovered stage ids',
  'scripts': ('act000',
              'act0',
              'act001',
              'act01',
              'act01_yl',
              'act01_yl1',
              'act01_zy',
              'act01_zy01',
              'act01_zy02',
              'act01_zy03',
              'act01_zy04',
              'act01_zy05',
              'act02',
              'act101',
              'act103a',
              'act103b',
              'act104',
              'act118a_new',
              'act118b_new',
              'act136',
              'act1001',
              'act1001a',
              'act1009',
              'act1103',
              'act1111',
              'act1120',
              'act1130',
              'act1148',
              'act1163',
              'act1165',
              'act1170',
              'act1180',
              'act1190',
              'act_1030',
              'act_1048',
              'act_1065',
              'act_70110201',
              'act_70110201try',
              'act_70110202try',
              'act_70110203',
              'act_70110203try',
              'act_70110204',
              'act_70110204try',
              'act_70110301try',
              'act_70110302try',
              'act_70110303try',
              'act_70110401',
              'act_70110401try',
              'act_70110501',
              'act_70110501try',
              'act_70110502',
              'act_70110502try',
              'act_70110601try',
              'act_70110901try',
              'act_bh1',
              'act_bh2',
              'act_ceshi',
              'act_chase',
              'act_chase0',
              'act_event1-1',
              'act_event1-3',
              'act_event2-2',
              'act_event2-3',
              'act_event3-1',
              'act_event3-1_new',
              'act_event3-2',
              'act_event3-3',
              'act_event3-4',
              'act_event3-5',
              'act_event3-6',
              'act_event5-3',
              'act_event7-1',
              'act_hangup',
              'act_hangup2',
              'act_kaohe1',
              'act_kaohe2',
              'act_mission2-1',
              'act_mission3-1',
              'act_plane1',
              'act_plane2',
              'act_show',
              'act_signal',
              'act_signal1',
              'act_signal2',
              'act_task8',
              'act_task16',
              'act_task18',
              'act_task19',
              'acta',
              'actb',
              'activity_op')},
 {'key': 'basic_drama_misc_scripts',
  'label': 'basic drama config and branch scripts',
  'scripts': ('drama1_1',
              'drama1_3',
              'drama1_4',
              'drama_000',
              'drama_001',
              'drama_bh',
              'drama_cfg')},
 {'key': 'beach_qte_drama_scripts',
  'label': 'beach event QTE drama scripts',
  'scripts': ('beachqte1',
              'beachqte2',
              'beachqte3',
              'beachqte4',
              'beachqte5',
              'beachqte6',
              'beachqte7',
              'beachqte8',
              'beachqte9',
              'beachqte10',
              'beachqte11',
              'beachqte12',
              'beachqte13',
              'beachqte14')},
 {'key': 'bus_route_drama_scripts',
  'label': 'bus route drama scripts',
  'scripts': ('bus1',
              'bus_1_1',
              'bus_1_3',
              'bus_1_21',
              'bus_1_31',
              'bus_2_1',
              'bus_2_3',
              'bus_2_12',
              'bus_2_32',
              'bus_3_1',
              'bus_3_3',
              'bus_3_13',
              'bus_3_23')},
 {'key': 'campaign_open_drama_scripts',
  'label': 'campaign opening drama scripts',
  'scripts': ('campaign_open_1',
              'campaign_open_2',
              'campaign_open_3',
              'campaign_open_3_1',
              'campaign_open_3_2',
              'campaign_open_4',
              'campaign_open_5',
              'campaign_open_6_1',
              'campaign_open_6_2')},
 {'key': 'card_guide_drama_scripts',
  'label': 'card tutorial guide drama scripts',
  'scripts': ('cardguide_1', 'cardguide_2')},
 {'key': 'chase_drama_scripts',
  'label': 'chase and vehicle QTE drama scripts',
  'scripts': ('chase01',
              'chase01_fail',
              'chase01_suc',
              'chase02',
              'chase03',
              'chase04',
              'chase05',
              'chase06',
              'chase07',
              'chase08',
              'chase09',
              'chase_\\x0ehuoming',
              'chase_end',
              'chase_end1',
              'chase_end_new',
              'chase_end_new2',
              'chase_fail',
              'chase_juqing1',
              'chase_qte_qiche1',
              'chase_qte_qiche2',
              'chase_qte_qiche3',
              'chase_qte_qiche4',
              'chase_qte_qiche5',
              'chase_rush1',
              'chase_rush2',
              'chase_rush3',
              'chase_rush4',
              'chase_texie',
              'chase_tips_lvgu',
              'chase_xy_300',
              'chase_xy_end',
              'chase_xy_start',
              'chase_yaogan',
              'chasefxy_maopao')},
 {'key': 'city_patrol_drama_scripts',
  'label': 'city patrol branch drama scripts',
  'scripts': ('cp_1_2',
              'cp_1_3',
              'cp_1_4',
              'cp_2_1',
              'cp_3_1',
              'cp_4_1',
              'cp_5_1',
              'cp_6_1',
              'cp_7_1',
              'cp_8_1',
              'cp_9_1',
              'cp_10\\t07021',
              'cp_10_1',
              'cp_11_1',
              'cp_12_1',
              'cp_13',
              'cp_13_1',
              'cp_13_2',
              'cp_13_3',
              'cp_13_4',
              'cp_14_1',
              'cp_14_2',
              'cp_14_3',
              'cp_14_4',
              'cp_15_1',
              'cp_16_1',
              'cp_17_1',
              'cp_18_1',
              'cp_19_1',
              'cp_20_1',
              'cp_21_1',
              'cp_22_1',
              'cp_23_1',
              'cp_24_1',
              'cp_1000801_1',
              'cp_1000801_2',
              'cp_1000801_3')},
 {'key': 'class_training_misc_scripts',
  'label': 'class training miscellaneous drama scripts',
  'scripts': ('tch_1',
              'tch_2',
              'tch_3',
              'tch_4',
              'tch_5',
              'tp_1',
              'tp_2',
              'tp_3',
              'tp_4')},
 {'key': 'combat_branch_misc_scripts',
  'label': 'combat branch miscellaneous drama scripts',
  'scripts': ('bd_1',
              'bd_2',
              'bd_3',
              'bd_4',
              'kn3_2_1',
              'kn3_2_4',
              'kn3_4_4boss',
              'kn5_5_6',
              'smash',
              'smash1',
              'smash2')},
 {'key': 'companion_event_misc_scripts',
  'label': 'companion event miscellaneous drama scripts',
  'scripts': ('egg_blackcat',
              'egg_cat1',
              'egg_cat2',
              'egg_cat3',
              'egg_cat4',
              'egg_cat5',
              'xz099',
              'xz100',
              'xz101',
              'xz_auto',
              'xz_f',
              'zy1-1',
              'zy1-2',
              'zy1-2b',
              'zy2-1',
              'zy2-1s',
              'zy-buji')},
 {'key': 'death_usj_misc_scripts',
  'label': 'Death Arms and USJ miscellaneous drama scripts',
  'scripts': ('death01', 'death02', 'death03', 'death_zx_usj_007')},
 {'key': 'event_branch_drama_scripts',
  'label': 'event branch drama scripts',
  'scripts': ('event1-1-1',
              'event1-1-1_boss',
              'event1-1-1_xiaoguai',
              'event1-1-2',
              'event1-2-2',
              'event1-2-4_shuinan',
              'event1-3-1',
              'event1_3_4',
              'event2-1-3',
              'event2-2-1',
              'event2-2-2',
              'event2-3-5-1',
              'event2-3-5-2',
              'event3-4-1',
              'event3-6-4',
              'event3-6-6',
              'event4035_1_1',
              'event4035_1_2',
              'event_4_2_2')},
 {'key': 'field_activity_drama_scripts',
  'label': 'field activity drama scripts',
  'scripts': ('huodong_ljhs01',
              'huodong_ljhs02',
              'huodong_ljhs03',
              'huodong_ljhs04',
              'huodong_ljhs05',
              'huodong_ljhs06',
              'huodong_ljhs07',
              'huodong_ljhs08',
              'huodong_ljhs09',
              'huodong_ljhs10',
              'huodong_tyj01',
              'huodong_tyj02',
              'huodong_tyj03',
              'huodong_tyj04',
              'huodong_tyj05')},
 {'key': 'hero_side_branch_misc_scripts',
  'label': 'hero side branch miscellaneous drama scripts',
  'scripts': ('adw_1',
              'adw_21',
              'adw_22',
              'hks_1',
              'hks_12',
              'hks_21',
              'hks_22',
              'os_1',
              'os_21',
              'os_22',
              'sbm_1',
              'sbm_21',
              'sbm_22',
              'sty_1',
              'sty_21',
              'sty_22')},
 {'key': 'joint_training_drama_scripts',
  'label': 'joint training branch drama scripts',
  'scripts': ('jz_101_1',
              'jz_201_1',
              'jz_201_2',
              'jz_301_1',
              'jz_401_1',
              'jz_401_2',
              'jz_401_3',
              'jz_501_1',
              'jz_501_2',
              'jz_601_1',
              'jz_601_2',
              'jz_601_3',
              'jz_701_1',
              'jz_701_2',
              'jz_701_3',
              'jz_801_1',
              'jz_801_2',
              'jz_901_1',
              'jz_901_2',
              'jz_901_3',
              'jz_901_4',
              'jzjt_1',
              'jzjt_2',
              'jzjt_3')},
 {'key': 'night_branch_drama_scripts',
  'label': 'night branch drama scripts',
  'scripts': ('night2-1-3BOSS',
              'night2-2-3BOSS',
              'night2-3-3BOSS',
              'night2-4-3BOSS',
              'nightarea',
              'nightarea-speciel')},
 {'key': 'pvp_guide_drama_scripts',
  'label': 'PVP tutorial guide drama scripts',
  'scripts': ('pvp_guide_camera',
              'pvpguide_001',
              'pvpguide_002',
              'pvpguide_003',
              'pvpguide_004',
              'pvpguide_005',
              'pvpguide_006',
              'pvpguide_007')},
 {'key': 'scenario_journey_drama_scripts',
  'label': 'scenario journey drama scripts',
  'scripts': ('sj_50102_1',
              'sj_50106',
              'sj_50107',
              'sj_50602_1',
              'sj_50602_2',
              'sj_51101_1',
              'sj_52402',
              'sj_52403',
              'sj_52404',
              'sj_52405',
              'sj_52406',
              'sj_5010301',
              'sj_5010302',
              'sj_5010503',
              'sj_5050201')},
 {'key': 'secret_branch_drama_scripts',
  'label': 'secret branch drama scripts',
  'scripts': ('secret2-1',
              'secret2-2',
              'secret2-3',
              'secret3_1',
              'secret3_2',
              'secret3_3',
              'secret3_4')},
 {'key': 'shiliguan_drama_scripts',
  'label': 'shiliguan challenge drama scripts',
  'scripts': ('shiliguan00',
              'shiliguan01',
              'shiliguan02',
              'shiliguan03',
              'shiliguan04',
              'shiliguan05',
              'shiliguan06',
              'shiliguan07',
              'shiliguan08')},
 {'key': 'slg_talking_drama_scripts',
  'label': 'strategy talking drama scripts',
  'scripts': ('slgGalking_syj03',
              'slgtalking001',
              'slgtalking002',
              'slgtalking003_1',
              'slgtalking004',
              'slgtalking005',
              'slgtalking006',
              'slgtalking007',
              'slgtalking009',
              'slgtalking009_1',
              'slgtalking0021',
              'slgtalking0022',
              'slgtalking0050',
              'slgtalking0052',
              'slgtalking0053',
              'slgtalking_sy\\x1701',
              'slgtalking_syj02')},
 {'key': 'stage_guide_drama_scripts',
  'label': 'stage tutorial guide drama scripts',
  'scripts': ('stageguide04_1',
              'stageguide_00',
              'stageguide_01',
              'stageguide_02',
              'stageguide_04',
              'stageguide_05',
              'stageguide_09',
              'stageguide_10')},
 {'key': 'tc_extra_drama_scripts',
  'label': 'TC prefixed extra drama scripts',
  'scripts': ('tc_11_2',
              'tc_202101_1',
              'tc_301202_1',
              'tc_301202_2',
              'tc_301202_3',
              'tc_402009!1',
              'tc_402009_2',
              'tc_402009_3',
              'tc_402009_4',
              'tc_801203_1',
              'tc_801203_2',
              'tc_801203_3',
              'tc_1001101_1')},
 {'key': 'training_yard_extra_drama_scripts',
  'label': 'training-yard extra drama scripts',
  'scripts': ('tyj_400111',
              'tyj_400112',
              'tyj_400113',
              'tyj_400114',
              'tyj_400115',
              'tyj_400116',
              'tyj_400117',
              'tyj_400118',
              'tyj_400121',
              'tyj_400122',
              'tyj_400123',
              'tyj_400124',
              'tyj_890001_1',
              'tyj_890003_1')},
 {'key': 'tx_branch_drama_scripts',
  'label': 'TX branch and training drama scripts',
  'scripts': ('tx1_1',
              'tx1_1_1',
              'tx1_1_1a',
              'tx1_1_1b',
              'tx1_1_2',
              'tx1_1_4',
              'tx1_1_4boss',
              'tx1_1_4end',
              'tx1_2',
              'tx1_2_4boss',
              'tx1_2_4end',
              'tx1_3',
              'tx1_3_4',
              'tx1_3_4end',
              'tx1_4',
              'tx1_4_4',
              'tx1_4_4end',
              'txbw_1',
              'txbw_2',
              'txbw_3',
              'txbw_4',
              'txbw_6',
              'txbw_7',
              'txbw_8')},
 {'key': 'xht_extra_drama_scripts',
  'label': 'XHT extra drama scripts',
  'scripts': ('xht_102',
              'xht_103',
              'xht_202',
              'xht_203',
              'xht_302',
              'xht_303',
              'xht_402',
              'xht_403',
              'xht_502',
              'xht_503',
              'xht_602',
              'xht_603',
              'xht_702',
              'xht_703',
              'xht_802',
              'xht_803',
              'xht_902',
              'xht_903',
              'xht_102301_1',
              'xht_103301_1',
              'xht_202301_1',
              'xht_203301_1',
              'xht_302301_1',
              'xht_303301_1',
              'xht_402301_1',
              'xht_403301_1',
              'xht_502301_1',
              'xht_503301_1',
              'xht_602301_1',
              'xht_603301_1',
              'xht_702301_1',
              'xht_703301_1',
              'xht_802301_1',
              'xht_803301_1',
              'xht_902301_1',
              'xht_903301_1')},
 {'key': 'zx_uppercase_branch_scripts',
  'label': 'uppercase ZX branch drama scripts',
  'scripts': ('ZX-1-1-1',
              'ZX-1-1-2',
              'ZX-1-1-2-1',
              'ZX-1-1-2-2',
              'ZX-1-1-4',
              'ZX-1-1-5',
              'ZX-1-2-1',
              'ZX-3-1-3',
              'ZX-3-1-3-1',
              'ZX-3-1-3-2',
              'ZX-3-1-5',
              'ZX-3-1-5-1',
              'ZX-3-2-2-1',
              'ZX-3-2-2-2',
              'ZX-3-2-4-1',
              'ZX-3-2-4-2',
              'ZX-3-2-5-1')}]
)

DRAMA_FAMILY_STAGE_BY_KEY = {stage.key: stage for stage in DRAMA_FAMILY_STAGES}

